# Generated by Django 4.1.3 on 2022-11-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nome do produto')),
                ('price', models.CharField(max_length=10, verbose_name='Preço do produto')),
                ('date', models.DateTimeField(verbose_name='Data de produção')),
            ],
        ),
    ]
