# Generated by Django 4.1.7 on 2023-04-26 14:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='suplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suplier',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
