# Generated by Django 4.1.7 on 2023-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_suplier_avatar_suplier_created_at_suplier_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
