# Generated by Django 4.1.7 on 2023-04-26 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_alter_suplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
